
-- Create a table to store your articles
CREATE TABLE public.articles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text,
  content text,
  image_url text,
  author_name text,
  author_avatar_url text,
  published_date timestamptz not null,
  category text,
  created_at timestamptz default now() not null
);

-- Add comments to explain the columns
COMMENT ON TABLE public.articles IS 'Stores blog articles for the Dental AI Insights website.';
COMMENT ON COLUMN public.articles.slug IS 'URL-friendly identifier for the article.';
COMMENT ON COLUMN public.articles.published_date IS 'The date the article was published.';

-- Enable Row Level Security (RLS) to control access to data.
-- This is a security best practice.
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone (including non-logged-in visitors)
-- to read the articles. This makes your blog public.
CREATE POLICY "Allow public read access to articles"
ON public.articles
FOR SELECT
USING (true);

-- Seed the table with your current articles
INSERT INTO public.articles (slug, title, excerpt, content, image_url, author_name, author_avatar_url, published_date, category)
VALUES
('the-rise-of-ai-in-dental-diagnostics', 'The Rise of AI in Dental Diagnostics', 'Artificial intelligence is transforming how dentists diagnose conditions, from cavities to oral cancers. Discover the latest breakthroughs.', '<p>The integration of artificial intelligence (AI) in dental diagnostics marks a significant leap forward for the field. By leveraging machine learning algorithms, dentists can now analyze radiographs with unprecedented accuracy, identifying early signs of decay and periodontal disease long before they become visible to the naked eye.</p><p>AI-powered systems are trained on vast datasets of dental images, enabling them to recognize subtle patterns that may elude human observation. This not only enhances diagnostic precision but also streamlines the clinical workflow, allowing for more efficient patient care.</p><h2>Key Applications</h2><ul><li>Automated caries detection on bitewing radiographs.</li><li>Early identification of periapical lesions.</li><li>Assessment of bone loss for periodontal disease diagnosis.</li><li>Cephalometric analysis for orthodontics.</li></ul><p>As technology continues to evolve, the role of AI in dentistry is set to expand, promising a future where diagnostics are faster, more accurate, and more accessible than ever before.</p>', 'https://images.unsplash.com/photo-1629904850761-e8b4de3d932b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3', 'Dr. Evelyn Reed', 'https://i.pravatar.cc/150?img=1', '2025-06-10', 'Industry'),
('how-ai-is-revolutionizing-dental-practice-management', 'How AI is Revolutionizing Dental Practice Management', 'From scheduling appointments to managing patient records, AI is streamlining the administrative side of dental clinics, freeing up time for patient care.', '<p>Beyond the clinical applications, AI is making significant waves in dental practice management. AI-driven software is automating tedious administrative tasks, leading to increased efficiency and reduced operational costs.</p><p>These systems can optimize appointment scheduling to minimize downtime, automate insurance claim processing, and provide valuable insights into practice performance through data analytics. By handling the backend operations, AI allows dental professionals to focus on what they do best: providing exceptional patient care.</p><h2>Transforming Operations</h2><ul><li>Intelligent appointment scheduling and reminders.</li><li>Automated billing and insurance verification.</li><li>Predictive analytics for patient flow and resource allocation.</li><li>Personalized patient communication and follow-ups.</li></ul><p>The adoption of AI in practice management is not just about technology; it''s about creating a more patient-centric and efficient dental practice for the modern era.</p>', 'https://images.unsplash.com/photo-15518b5338-b03a761827a8?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3', 'John Carter', 'https://i.pravatar.cc/150?img=2', '2025-06-05', 'Tools'),
('top-5-ai-powered-tools-for-modern-dentists', 'Top 5 AI-Powered Tools for Modern Dentists', 'A curated list of the most impactful AI tools that are changing the game for clinicians and dental clinics worldwide.', '<p>The market is now brimming with innovative AI-powered tools designed to support dental professionals. Navigating the options can be challenging, so we''ve compiled a list of top-tier solutions that are making a real difference.</p><p>From diagnostic aids to treatment planning software, these tools are at the forefront of the dental technology revolution. They empower dentists with data-driven insights, improve treatment outcomes, and enhance the overall patient experience.</p><h2>Must-Have AI Tools</h2><ol><li><strong>Overjet:</strong> An FDA-cleared AI platform for analyzing dental radiographs and quantifying disease.</li><li><strong>Pearl:</strong> Offers a suite of AI solutions for pathology detection and practice intelligence.</li><li><strong>DentalMonitoring:</strong> A remote monitoring solution that uses AI to track treatment progress, especially in orthodontics.</li><li><strong>VideaHealth:</strong> Provides AI-powered diagnostics to help dentists detect diseases earlier and more accurately.</li><li><strong>Pre-op:</strong> AI-based treatment planning software for restorative dentistry and implantology.</li></ol><p>Investing in these tools can provide a significant return, not just financially, but in the quality of care delivered to patients.</p>', 'https://images.unsplash.com/photo-1580281658223-9b93f18ae9ae?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3', 'Dr. Anya Sharma', 'https://i.pravatar.cc/150?img=3', '2025-05-28', 'Research');

